### ISSUE TITLE
'uc_pp_avr' is not defined

### ISSUE THREAD

**Issue by I-Knight-I** [DGA-MI-SSI/unicorn-ppc#2]
unicorn.py, line 432. No definition for 'uc_pp_avr'. 
Also no definition for 'uc_ppc_avr' either. 

I thought it might've been a typo so checked for 'uc_ppc_avr' - which also doesn't exist and is used on line 370.

**Comment by ghost** [comment]
Hello ! 

The latest commit in 2c7d6cf should include a definition of the appropriate structure to fix this error, as well as remove the typo. 

Does it do the trick ?

**Comment by I-Knight-I** [comment]
Hey, thanks for the quick response.

I'll be sure to compile it in 12 minutes when Make is no longer crying about the files being from the future ;)

E: Yup, that's worked. Thanks a lot!
